# Generated by Django 2.0 on 2017-12-17 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField()),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('U', 'user'), ('O', 'organisation')], max_length=1)),
                ('url', models.URLField()),
                ('avatar_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('language', models.CharField(choices=[('js', 'javascript'), ('py', 'python')], max_length=2)),
                ('source', models.CharField(choices=[('n', 'npm'), ('p', 'pypi')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('remote_id', models.IntegerField()),
                ('name', models.TextField()),
                ('full_name', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('source', models.CharField(choices=[('gh', 'github')], default='gh', max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precident.Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='package',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='precident.Repo'),
        ),
    ]
