# Generated by Django 2.0 on 2017-12-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='source',
            field=models.CharField(choices=[('gh', 'github')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
