# Generated by Django 2.0 on 2018-01-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedent', '0002_owner_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
