# Generated by Django 2.0 on 2018-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedent', '0003_repo_description_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='login',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
