# Generated by Django 2.0 on 2018-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precedent', '0004_owner_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
            ],
        ),
    ]
